name: Build macOS DMG

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'

      - name: Build macOS App
        run: |
          flutter config --enable-macos-desktop
          flutter build macos --release
          
      - name: Verify Build Existence
        run: ls -la build/macos/Build/Products/Release/

      - name: Install create-dmg
        run: npm install -g create-dmg

      - name: Create DMG
        run: |
          create-dmg \
            --dmg-title="Mail Sender" \
            --overwrite \
            --quit-after-done \
            "build/macos/Build/Products/Release/mail_sender.app" \
            "build/macos"

      - name: Upload DMG
        uses: actions/upload-artifact@v4
        with:
          name: mail_sender.dmg
          path: build/macos/*.dmg
